[profile.default]
src = "course"
out = "out"
libs = ["lib"]
match_path = "*/*.t.sol"
ffi = true
evm_version = "shanghai"
ignored_error_codes = [
    2519, # Warning (2519): This declaration shadows an existing declaration.
    1878 # Warning (1878): SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
]

[rpc_endpoints]
mainnet = "https://rpc.ankr.com/eth"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config